name:                orestes
version:             0.2.0.1
github:              "codepr/orestes"
license:             BSD3
author:              "Andrea Giacomo Baldan"
maintainer:          "a.g.baldan@gmail.com"
copyright:           "2016-2018 Andrea Giacomo Baldan"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/codepr/orestes#readme>

dependencies:
- base >= 4.7 && < 5
- network >= 2.6 && < 2.7
- containers >=0.5 && < 0.6
- bytestring >= 0.10 && < 0.11
- stm
- distributed-process <= 0.7.4
- distributed-process-simplelocalnet <= 0.2.4
- binary
- hashable

library:
  source-dirs: src

executables:
  orestes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - orestes

tests:
  orestes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - orestes
